#!/bin/sh
if git show-ref --quiet "refs/heads/$1" "refs/remotes/$1"; then
	git log --decorate "$1" | awk '
		/^commit / {
			if (other) exit
			if (NR > 1 && /\)$/) other = 1
		}
		//'
else
	git show --decorate --format=fuller -p --numstat "$1"
fi
