#!/bin/sh
exec 2>/dev/null
case "$1" in
*...*)
	git range-diff "$1" && exit ;;
*..*)
	git log --oneline --decorate "$1" && exit ;;
esac
if git show-ref --quiet "$1"; then
	trylog() {
		outp="$(git log --oneline --decorate "$@")"
		if [ -n "$outp" ]; then
			echo "$outp"
			exit
		fi
	}
	trylog "$1" ^origin 
	trylog --first-parent --exclude-first-parent-only "$1" ^origin
	trylog "$1"
fi
exec git show --decorate --format=fuller -p --numstat "$1"
