#!/bin/sh -e
if [ -n "$1" ]; then
	set -- "refs/heads/$1" "refs/remotes/*/$1"
else
	set -- "refs/heads/*"
fi
set -- git -P for-each-ref --format='%09%(refname)' --sort=-committerdate "$@"
git-repos | yargs indir '{}' "$@" | awk '
	$0 !~ /\/HEAD$/ {
		sub(/^\trefs\/(heads|remotes)\//, "\t")
		print
	}'
