#!/bin/sh -e
temp="$(mktemp)"
CLEANUP="rm -f '$temp'" . trap.sh
for file; do
	[ -e "$file" -a ! -d "$file" ] || continue
	info="$(git ls-files --full-name --stage "$file")"
	mode="${info%%[^0-9]*}"
	path="${info#*	}"
	git show :"$path" >"$temp"
	if [ -n "$ACMEVIMPORT" ]; then
		avim -o "$file"
		avim -d "$file" "$temp"
	else
		vim -d "$file" "$temp"
	fi
	hash="$(git hash-object -w "$temp")"
	git update-index --cacheinfo "$mode,$hash,$path"
done
