#!/bin/sh
exec 2>/dev/null
case "$1" in
*...*)
	git range-diff "$1" && exit ;;
*..*)
	git log --oneline --decorate "$1" && exit ;;
esac
if git show-ref --quiet "$1"; then
	log="$(git log --oneline --decorate "$1" \
		"^$(git merge-base --octopus "$1" $(git remote))")"
	[ -n "$log" ] && { echo "$log"; exit; }
fi
exec git show --decorate --format=fuller -p --numstat "$1"
