#!/bin/sh -e
if [ $# -gt 0 ]; then
	f="$1"
else
	f="$(mktemp /tmp/ped.XXXXXX)"
	CLEANUP="rm -f '$f'" . trap.sh
fi
cat >"$f"
(
	[ -t 2 ] && exec </dev/tty >/dev/tty
	exec ${EDITOR:-ed} "$f"
)
cat "$f"
