#!/bin/sh -e
host="$1"
file="$2"
shift 2
base="$(basename "$file")"
rfile="$(cd "$(dirname "$file")"; pwd -L)/$base"
rfile="${rfile#$HOME/}"
temp="$(mktemp "/tmp/$base.XXXXXXXX")"
CLEANUP="rm -f '$temp'" . trap.sh
echo "Download $file"
scp "$@" "$host:$rfile" "$temp"
if [ -n "$ACMEVIMPORT" -a -e "$file" ]; then
	avim -o "$file"
	avim -d "$file" "$temp"
else
	${EDITOR:-ed} "$temp"
fi
echo "Upload $file"
scp "$@" "$temp" "$host:$rfile"
