#!/bin/sh -e
host="$1"
file="$2"
shift 2
base="$(basename "$file")"
rfile="$(cd "$(dirname "$file")"; pwd -L)/$base"
rfile="${rfile#$HOME/}"
temp="$(mktemp "/tmp/$base.XXXXXXXX")"
CLEANUP="rm -f '$temp'" . trap.sh
echo "Download $file"
scp "$host:$rfile" "$temp" && r=0 || r=$?
[ $r -le 1 ]
[ -e "$file" ] && orig="$file" || orig="/dev/null"
diff="$(diff -u "$orig" "$temp" || :)"
[ -z "$diff" ] && exit
diff="$(echo "$diff" | ped)"
[ -n "$diff" ] && echo "$diff" | patch -up0 "$file"
cmp -s "$file" "$temp" && exit
echo "Upload $file"
scp "$@" "$file" "$host:$rfile"
